/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisId = string;
export interface AnalysisRecord {
  'id' : AnalysisId,
  'status' : AnalysisStatus,
  'overallScore' : number,
  'owner' : UserId,
  'fileSize' : bigint,
  'uploadTimestamp' : Timestamp,
  'verdict' : Verdict,
  'filename' : string,
  'frameAnalysis' : FrameAnalysis,
  'forensic' : ForensicBreakdown,
}
export type AnalysisStatus = { 'Queued' : null } |
  { 'Failed' : null } |
  { 'Complete' : null } |
  { 'Processing' : null };
export interface FlaggedFrame {
  'suspicionScore' : number,
  'frameIndex' : bigint,
}
export interface ForensicBreakdown {
  'frameInsertionRisk' : number,
  'compressionArtifactScore' : number,
  'deepfakeProbability' : number,
  'frameDeletionRisk' : number,
  'temporalInconsistencyScore' : number,
  'audioVideoSyncScore' : number,
}
export interface FrameAnalysis {
  'frameCount' : bigint,
  'frameRate' : number,
  'colorAnomalyScore' : number,
  'flaggedFrames' : Array<FlaggedFrame>,
  'resolution' : string,
}
export type ShareToken = string;
export interface SubmitVideoMetadata {
  'frameCount' : [] | [bigint],
  'frameRate' : [] | [number],
  'resolution' : [] | [string],
}
export type Timestamp = bigint;
export type UserId = Principal;
export type Verdict = { 'Uncertain' : null } |
  { 'Fake' : null } |
  { 'Real' : null };
export interface _SERVICE {
  'deleteAnalysisRecord' : ActorMethod<[AnalysisId], boolean>,
  'generateShareToken' : ActorMethod<[AnalysisId], string>,
  'getAnalysisResult' : ActorMethod<[AnalysisId], [] | [AnalysisRecord]>,
  'getSharedAnalysis' : ActorMethod<[ShareToken], [] | [AnalysisRecord]>,
  'getUserHistory' : ActorMethod<[], Array<AnalysisRecord>>,
  'submitVideoAnalysis' : ActorMethod<
    [string, bigint, SubmitVideoMetadata],
    AnalysisId
  >,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];