/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const AnalysisId = IDL.Text;
  const AnalysisStatus = IDL.Variant({
    'Queued' : IDL.Null,
    'Failed' : IDL.Null,
    'Complete' : IDL.Null,
    'Processing' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Verdict = IDL.Variant({
    'Uncertain' : IDL.Null,
    'Fake' : IDL.Null,
    'Real' : IDL.Null,
  });
  const FlaggedFrame = IDL.Record({
    'suspicionScore' : IDL.Float64,
    'frameIndex' : IDL.Nat,
  });
  const FrameAnalysis = IDL.Record({
    'frameCount' : IDL.Nat,
    'frameRate' : IDL.Float64,
    'colorAnomalyScore' : IDL.Float64,
    'flaggedFrames' : IDL.Vec(FlaggedFrame),
    'resolution' : IDL.Text,
  });
  const ForensicBreakdown = IDL.Record({
    'frameInsertionRisk' : IDL.Float64,
    'compressionArtifactScore' : IDL.Float64,
    'deepfakeProbability' : IDL.Float64,
    'frameDeletionRisk' : IDL.Float64,
    'temporalInconsistencyScore' : IDL.Float64,
    'audioVideoSyncScore' : IDL.Float64,
  });
  const AnalysisRecord = IDL.Record({
    'id' : AnalysisId,
    'status' : AnalysisStatus,
    'overallScore' : IDL.Float64,
    'owner' : UserId,
    'fileSize' : IDL.Nat,
    'uploadTimestamp' : Timestamp,
    'verdict' : Verdict,
    'filename' : IDL.Text,
    'frameAnalysis' : FrameAnalysis,
    'forensic' : ForensicBreakdown,
  });
  const ShareToken = IDL.Text;
  const SubmitVideoMetadata = IDL.Record({
    'frameCount' : IDL.Opt(IDL.Nat),
    'frameRate' : IDL.Opt(IDL.Float64),
    'resolution' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'deleteAnalysisRecord' : IDL.Func([AnalysisId], [IDL.Bool], []),
    'generateShareToken' : IDL.Func([AnalysisId], [IDL.Text], []),
    'getAnalysisResult' : IDL.Func(
        [AnalysisId],
        [IDL.Opt(AnalysisRecord)],
        ['query'],
      ),
    'getSharedAnalysis' : IDL.Func(
        [ShareToken],
        [IDL.Opt(AnalysisRecord)],
        ['query'],
      ),
    'getUserHistory' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
    'submitVideoAnalysis' : IDL.Func(
        [IDL.Text, IDL.Nat, SubmitVideoMetadata],
        [AnalysisId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };