/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { type HttpAgentOptions, type ActorConfig, type Agent } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export interface AnalysisRecord {
    id: AnalysisId;
    status: AnalysisStatus;
    overallScore: number;
    owner: UserId;
    fileSize: bigint;
    uploadTimestamp: Timestamp;
    verdict: Verdict;
    filename: string;
    frameAnalysis: FrameAnalysis;
    forensic: ForensicBreakdown;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface FrameAnalysis {
    frameCount: bigint;
    frameRate: number;
    colorAnomalyScore: number;
    flaggedFrames: Array<FlaggedFrame>;
    resolution: string;
}
export type AnalysisId = string;
export interface SubmitVideoMetadata {
    frameCount?: bigint;
    frameRate?: number;
    resolution?: string;
}
export interface FlaggedFrame {
    suspicionScore: number;
    frameIndex: bigint;
}
export interface ForensicBreakdown {
    frameInsertionRisk: number;
    compressionArtifactScore: number;
    deepfakeProbability: number;
    frameDeletionRisk: number;
    temporalInconsistencyScore: number;
    audioVideoSyncScore: number;
}
export type ShareToken = string;
export enum AnalysisStatus {
    Queued = "Queued",
    Failed = "Failed",
    Complete = "Complete",
    Processing = "Processing"
}
export enum Verdict {
    Uncertain = "Uncertain",
    Fake = "Fake",
    Real = "Real"
}
export interface backendInterface {
    deleteAnalysisRecord(id: AnalysisId): Promise<boolean>;
    generateShareToken(id: AnalysisId): Promise<string>;
    getAnalysisResult(id: AnalysisId): Promise<AnalysisRecord | null>;
    getSharedAnalysis(token: ShareToken): Promise<AnalysisRecord | null>;
    getUserHistory(): Promise<Array<AnalysisRecord>>;
    submitVideoAnalysis(filename: string, fileSize: bigint, metadata: SubmitVideoMetadata): Promise<AnalysisId>;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export declare function createActor(canisterId: string, options: CreateActorOptions = {}): backendInterface;
