/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface AnalysisRecord {
    id: AnalysisId;
    status: AnalysisStatus;
    overallScore: number;
    owner: UserId;
    fileSize: bigint;
    uploadTimestamp: Timestamp;
    verdict: Verdict;
    filename: string;
    frameAnalysis: FrameAnalysis;
    forensic: ForensicBreakdown;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface FrameAnalysis {
    frameCount: bigint;
    frameRate: number;
    colorAnomalyScore: number;
    flaggedFrames: Array<FlaggedFrame>;
    resolution: string;
}
export type AnalysisId = string;
export interface SubmitVideoMetadata {
    frameCount?: bigint;
    frameRate?: number;
    resolution?: string;
}
export interface FlaggedFrame {
    suspicionScore: number;
    frameIndex: bigint;
}
export interface ForensicBreakdown {
    frameInsertionRisk: number;
    compressionArtifactScore: number;
    deepfakeProbability: number;
    frameDeletionRisk: number;
    temporalInconsistencyScore: number;
    audioVideoSyncScore: number;
}
export type ShareToken = string;
export enum AnalysisStatus {
    Queued = "Queued",
    Failed = "Failed",
    Complete = "Complete",
    Processing = "Processing"
}
export enum Verdict {
    Uncertain = "Uncertain",
    Fake = "Fake",
    Real = "Real"
}
export interface backendInterface {
    deleteAnalysisRecord(id: AnalysisId): Promise<boolean>;
    generateShareToken(id: AnalysisId): Promise<string>;
    getAnalysisResult(id: AnalysisId): Promise<AnalysisRecord | null>;
    getSharedAnalysis(token: ShareToken): Promise<AnalysisRecord | null>;
    getUserHistory(): Promise<Array<AnalysisRecord>>;
    submitVideoAnalysis(filename: string, fileSize: bigint, metadata: SubmitVideoMetadata): Promise<AnalysisId>;
}
import type { AnalysisId as _AnalysisId, AnalysisRecord as _AnalysisRecord, AnalysisStatus as _AnalysisStatus, ForensicBreakdown as _ForensicBreakdown, FrameAnalysis as _FrameAnalysis, SubmitVideoMetadata as _SubmitVideoMetadata, Timestamp as _Timestamp, UserId as _UserId, Verdict as _Verdict } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async deleteAnalysisRecord(arg0: AnalysisId): Promise<boolean> {
        const result = await this.actor.deleteAnalysisRecord(arg0);
        return result;
    }
    async generateShareToken(arg0: AnalysisId): Promise<string> {
        const result = await this.actor.generateShareToken(arg0);
        return result;
    }
    async getAnalysisResult(arg0: AnalysisId): Promise<AnalysisRecord | null> {
        const result = await this.actor.getAnalysisResult(arg0);
        return from_candid_opt_n1(result);
    }
    async getSharedAnalysis(arg0: ShareToken): Promise<AnalysisRecord | null> {
        const result = await this.actor.getSharedAnalysis(arg0);
        return from_candid_opt_n1(result);
    }
    async getUserHistory(): Promise<Array<AnalysisRecord>> {
        const result = await this.actor.getUserHistory();
        return from_candid_vec_n8(result);
    }
    async submitVideoAnalysis(arg0: string, arg1: bigint, arg2: SubmitVideoMetadata): Promise<AnalysisId> {
        const result = await this.actor.submitVideoAnalysis(arg0, arg1, to_candid_SubmitVideoMetadata_n9(arg2));
        return result;
    }
}
function from_candid_AnalysisRecord_n2(value: _AnalysisRecord): AnalysisRecord {
    return from_candid_record_n3(value);
}
function from_candid_AnalysisStatus_n4(value: _AnalysisStatus): AnalysisStatus {
    return from_candid_variant_n5(value);
}
function from_candid_Verdict_n6(value: _Verdict): Verdict {
    return from_candid_variant_n7(value);
}
function from_candid_opt_n1(value: [] | [_AnalysisRecord]): AnalysisRecord | null {
    return value.length === 0 ? null : from_candid_AnalysisRecord_n2(value[0]);
}
function from_candid_record_n3(value: {
    id: _AnalysisId;
    status: _AnalysisStatus;
    overallScore: number;
    owner: _UserId;
    fileSize: bigint;
    uploadTimestamp: _Timestamp;
    verdict: _Verdict;
    filename: string;
    frameAnalysis: _FrameAnalysis;
    forensic: _ForensicBreakdown;
}): {
    id: AnalysisId;
    status: AnalysisStatus;
    overallScore: number;
    owner: UserId;
    fileSize: bigint;
    uploadTimestamp: Timestamp;
    verdict: Verdict;
    filename: string;
    frameAnalysis: FrameAnalysis;
    forensic: ForensicBreakdown;
} {
    return {
        id: value.id,
        status: from_candid_AnalysisStatus_n4(value.status),
        overallScore: value.overallScore,
        owner: value.owner,
        fileSize: value.fileSize,
        uploadTimestamp: value.uploadTimestamp,
        verdict: from_candid_Verdict_n6(value.verdict),
        filename: value.filename,
        frameAnalysis: value.frameAnalysis,
        forensic: value.forensic
    };
}
function from_candid_variant_n5(value: {
    Queued: null;
} | {
    Failed: null;
} | {
    Complete: null;
} | {
    Processing: null;
}): AnalysisStatus {
    return "Queued" in value ? AnalysisStatus.Queued : "Failed" in value ? AnalysisStatus.Failed : "Complete" in value ? AnalysisStatus.Complete : "Processing" in value ? AnalysisStatus.Processing : value;
}
function from_candid_variant_n7(value: {
    Uncertain: null;
} | {
    Fake: null;
} | {
    Real: null;
}): Verdict {
    return "Uncertain" in value ? Verdict.Uncertain : "Fake" in value ? Verdict.Fake : "Real" in value ? Verdict.Real : value;
}
function from_candid_vec_n8(value: Array<_AnalysisRecord>): Array<AnalysisRecord> {
    return value.map((x)=>from_candid_AnalysisRecord_n2(x));
}
function to_candid_SubmitVideoMetadata_n9(value: SubmitVideoMetadata): _SubmitVideoMetadata {
    return to_candid_record_n10(value);
}
function to_candid_record_n10(value: {
    frameCount?: bigint;
    frameRate?: number;
    resolution?: string;
}): {
    frameCount: [] | [bigint];
    frameRate: [] | [number];
    resolution: [] | [string];
} {
    return {
        frameCount: value.frameCount ? candid_some(value.frameCount) : candid_none(),
        frameRate: value.frameRate ? candid_some(value.frameRate) : candid_none(),
        resolution: value.resolution ? candid_some(value.resolution) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
